from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
browser = webdriver.Firefox()

browser.get('https://practiceselenium.com')
button = browser.find_element_by_id('wsb-element-00000000-0000-0000-0000-000450914890')
button.click()
button = browser.find_element_by_id('wsb-element-00000000-0000-0000-0000-000451959280')
button.click()
browser.implicitly_wait(5)
email = browser.find_element_by_id('email')
email.send_keys('test@selenium.com')
name = browser.find_element_by_id('name')
name.send_keys('John Test')
address = browser.find_element_by_id('address')
address.send_keys('1001 Selenium Ave, Tulsa, OK 00000')
card_type = Select(browser.find_element_by_id('card_type'))
card_type.select_by_visible_text('Visa')
card_number = browser.find_element_by_id('card_number')
card_number.send_keys('4000000000000000')
cardholder_name = browser.find_element_by_id('cardholder_name')
cardholder_name.send_keys('John Test')
verification_code = browser.find_element_by_id('verification_code')
verification_code.send_keys('321')
browser.implicitly_wait(5)
button = browser.find_element_by_tag_name('button')
button.click()
#browser.close()